In [2]:
user_input=input("Enter the choice")
match user_input:
    case 'add':
        print("add")
        

Enter the choiceadd
add


# numpy 


In [5]:
import numpy as np


In [6]:
a1 = np.array([1,2,3,4,5])

In [7]:
a1

array([1, 2, 3, 4, 5])

In [8]:
print(a1)

[1 2 3 4 5]


In [9]:
print(type(a1))

<class 'numpy.ndarray'>


In [10]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([5,6,7,8,9])

In [11]:
print(a1 + a2)

[ 6  8 10 12 14]


In [13]:
print(a1 * 2)
print(a2 * 3)


[ 2  4  6  8 10]
[15 18 21 24 27]


In [16]:
l1 = [2,3,4,5]  # list trying to handle arithmetic operation
print(l1 * 3)

[2, 3, 4, 5, 2, 3, 4, 5, 2, 3, 4, 5]


In [17]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([5,6,7,8,9])
a1 - a2 

array([-4, -4, -4, -4, -4])

In [18]:
abs(a1 - a2)

array([4, 4, 4, 4, 4])

In [19]:
a1

array([1, 2, 3, 4, 5])

In [20]:
a1[1]

2

In [22]:
a1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,14])
a1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 14])

In [23]:
a1 = np.array([22,33,55,66,77,1,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,14])
a1


array([22, 33, 55, 66, 77,  1,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,
       12, 13, 14, 15, 14])

In [24]:
len(a1)

22

In [25]:
a1[::]

array([22, 33, 55, 66, 77,  1,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,
       12, 13, 14, 15, 14])

In [26]:
a1[0:5]

array([22, 33, 55, 66, 77])

In [27]:
a1[::2]

array([22, 55, 77,  1,  3,  5,  7,  9, 11, 13, 15])

In [28]:
a1

array([22, 33, 55, 66, 77,  1,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,
       12, 13, 14, 15, 14])

In [29]:
np.sort(a1)

array([ 1,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 14, 15,
       22, 33, 55, 66, 77])

In [30]:
a1

array([22, 33, 55, 66, 77,  1,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,
       12, 13, 14, 15, 14])

In [31]:
print(a1.ndim)

1


In [32]:
a1.size

22

In [33]:
print(len(a1))

22


In [37]:
a1.dtype
a1.itemsize

8

In [39]:
# a1 = np.array([2,3,4,5,6,7,8],dtype = float)
a1 = np.array([2,3,4,5,6,7,8],dtype = int)

In [40]:
a1.dtype

dtype('int32')

In [41]:
a1.itemsize

4

In [42]:
a1 = np.array([1,2,3,4,5])
a1

array([1, 2, 3, 4, 5])

In [44]:
#range 
a1 = np.arange(10)
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
a1 = np.arange(100)
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [46]:
a1 = np.arange(10,100)
a1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

In [49]:
a1 = np.arange(10,100,10)
a1

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [50]:
a1.shape

(9,)

In [51]:
a1 = np.array([[1,2,3,4,5],[7,8,9,10,11]])
a1

array([[ 1,  2,  3,  4,  5],
       [ 7,  8,  9, 10, 11]])

In [52]:
a1.shape

(2, 5)

In [53]:
a1.size

10

In [54]:
len(a1)

2

In [55]:
pwd

'C:\\Users\\Admin\\Data Science 1PM'