In [3]:
import numpy as np

In [5]:
arr1 = np.arange(1,11)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
arr2 = np.arange(10,20)
arr2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [7]:
arr1 * 2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [12]:
print(arr1 + arr2)

[11 13 15 17 19 21 23 25 27 29]


In [9]:
len(arr1)

10

In [10]:
len(arr2)

11

In [14]:
new_a1 = np.arange(1,16)
print(new_a1)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [16]:
print(new_a1.ndim)

1


In [17]:
print(new_a1.shape)

(15,)


In [18]:
new_a1 = np.arange(1,16).reshape(3,5)
print(new_a1)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [19]:
print(len(new_a1))

3


In [20]:
print(new_a1.size)

15


In [21]:
print(new_a1.shape)

(3, 5)


In [22]:
print(new_a1.dtype)

int32


In [28]:
a1 = np.array([2,3,4,5,6],dtype=float)
a1

array([2., 3., 4., 5., 6.])

In [40]:
a1 = np.array([2,3,4,5,6],dtype= float)
a1

array([2., 3., 4., 5., 6.])

In [41]:
a1.itemsize

8

In [43]:
a1 = np.array([2,3,4,5,6],dtype= int)
a1
a1.itemsize

4

In [44]:
a1 = np.array([2,3,4,5,6],dtype= int)
print(a1)

[2 3 4 5 6]


In [46]:
a1 = np.zeros([5,6])
a1

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [47]:
a1 = np.zeros([5,6],dtype=int)
a1

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [48]:
a1 = np.ones([5,6],dtype=int)
a1

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [55]:
a1 = np.eye(5,6)
a1

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.]])

In [59]:
a1 = np.arange(1,11)
a2 = np.arange(10,20)
a1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [58]:
a2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [64]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [66]:
arr[0][0]

1

In [67]:
arr[0][3]

4

In [68]:
arr[1][2]

8

In [70]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [71]:
arr.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [72]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
res = np.sum(arr)

In [73]:
res

55

In [84]:
arr1 = np.array([1,5,7,9,1,3,5])
print(arr1)
np.sort(arr1)

[1 5 7 9 1 3 5]


array([1, 1, 3, 5, 5, 7, 9])