In [1]:
import numpy as np

In [2]:
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])
print(a1)
print(a2)

[1 2 3]
[4 5 6]


In [5]:
a1 = np.array([1,2,3,4,5])
a1

array([1, 2, 3, 4, 5])

In [6]:
print(np.mean(a1))   # averagethe average of a data set, found by adding all numbers together and 
# then dividing the sum of the numbers by the number of numbers

3.0


In [7]:
a1 = np.array([1,2,5,7,9,111,22,333])
np.mean(a1)

61.25

In [13]:
n1 = sorted([1,2,5,7,9,111,22,12])
a1 = np.array(n1)
a1

array([  1,   2,   5,   7,   9,  12,  22, 111])

In [14]:
print(np.median(a1))  #  the middle number in a sorted ascending or descending list of numbers 

8.0


In [16]:
n1 = sorted([1,2,5,7,9,99,101,111,22,12,11])
a1 = np.array(n1)
a1

array([  1,   2,   5,   7,   9,  11,  12,  22,  99, 101, 111])

In [17]:
print(np.median(a1))

11.0


In [18]:
n1 = [1,2,5,7,9,99,101,111,22,12,11]
a1 = np.array(n1)
a1

array([  1,   2,   5,   7,   9,  99, 101, 111,  22,  12,  11])

In [19]:
print(np.median(a1))

11.0


In [20]:
print(np.std(a1))

42.751637153901406


In [22]:
n1 = [991,900,51,52,55,77,90,99,66,67,91,62,72,81]
a1 = np.array(n1)
print(np.mean(a1))
print(np.std(a1))

71.91666666666667
15.305000998221317


In [23]:
n1 = [51,51,51,52,51,53,56,57,51,52,62,51]
a1 = np.array(n1)
print(np.mean(a1))
print(np.std(a1))

53.166666666666664
3.3124344857252983


In [24]:
n1 = [991,900,51,52,55,77,90,99,66,67,91,62,72,81]
a1 = np.array(n1)
print(np.mean(a1))

196.71428571428572


In [25]:
# standard deviation
print(np.std(a1))

306.5015564098046


In [27]:
n1 = [91,90,51,52,55,77,90,99,66,67,91,62,72,81]
a1 = np.array(n1)
print(np.mean(a1))
print(np.std(a1))

74.57142857142857
15.591729885305432


In [28]:
n1 = [91,91,91,92,95,97,90,99,96,97,91,92,92,91]
a1 = np.array(n1)
print(np.mean(a1))
print(np.std(a1))

93.21428571428571
2.832933145007421
